Release 4.8.0
Release notes are available at:
https://docs.dremio.com/release-notes/48-release-notes.html

Change-Id: I69fb3427435c4567d93685cc06cd34a945f46a5d

diff --git a/distribution/resources/src/main/resources/bin/dremio-config b/distribution/resources/src/main/resources/bin/dremio-config
--- a/distribution/resources/src/main/resources/bin/dremio-config
+++ b/distribution/resources/src/main/resources/bin/dremio-config
@@ -166,7 +166,7 @@ if [ -z "$JAVA_HOME" ]; then
 +======================================================================+
 |      Error: JAVA_HOME is not set and Java could not be found         |
 +----------------------------------------------------------------------+
-| Dremio requires Java 1.8 or later.                                   |
+| Dremio requires Java 8 or later.                                   |
 +======================================================================+
 EOF
     exit 1
@@ -207,8 +207,13 @@ else
     exit 1
 fi
 
-if [ $JAVA_MAJOR_VERSION -lt 8 ]; then
-  echo "Java 1.8 or later is required to run Dremio."
+if [ "$DREMIO_JAVA_VERSION_CHECK" == "false" ]; then
+  if [ $JAVA_MAJOR_VERSION -lt 8 ]; then
+    echo "Java 8 or later is required to run Dremio."
+    exit 1
+  fi
+elif [ $JAVA_MAJOR_VERSION -ne 8 ]; then
+  echo "Java 8 is required to run Dremio. Java $JAVA_MAJOR_VERSION is being used."
   exit 1
 fi
 
